# Generated by Django 3.2.18 on 2023-04-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_auto_20230406_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerModel',
        ),
    ]
