# Generated by Django 3.2.18 on 2023-04-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_rename_customer_customermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
